const goaCombos = [
{
    title: "SCUBA DIVING AT ANDAMAN ISLAND",
    subtitle: "Best Scuba Diving for Non-Swimmers",
    oldPrice: "₹6,000",
    newPrice: "₹5,500",
    rating: "⭐ 4.9 (208 reviews)",
    features: [
      "North Bay Island, Andaman",
      "NO Swimming Skills Required",
      "Best For Beginners",
      "Scuba Diving at Andaman Island",
      "Scuba diving Training by PADI dive master",
      "Certified Scuba Dive Master accompany you underwater",
      "Boat Ride to Dive Location",
      "Photos & videos underwater (GoPro 10 camera underwater)",
      "Boat Trip | Sightseeing",
      "Maximum Depth 12 Metres",
      "Certified Scuba Trainer",
      "Free Pick up/drop",
      "Pre-Book it on 15% Discount",
      "Booking Amount is 1,000 INR/person",
    ],
  },
  {
    title: "SCUBA DIVING AT ROCK ISLAND",
    subtitle: "Gold Package - Full Experience Combo",
    oldPrice: "₹3,500",
    newPrice: "₹2,700",
    rating: "⭐ 4.6 (600 reviews)",
    features: [
      "Free Pick up/drop",
      "1.5 Hour Bus Journey to Jetty",
      "Short Sea Trip",
      "Scuba Training by PADI Diver",
      "Scuba Diving at Rock Island",
      "Scuba Head Cap",
      "Scuba Suite",
      "Scuba Cylinder",
      "Mouth Pump",
      "BCD Regulator",
      "Sightseeing",
      "Watersports",
      "Parasailing",
      "Speed Boat",
      "Jet Ski",
      "Banana Ride",
      "Bumper Ride",
      "Snorkeling (Complementary)",
      "Life Jacket",
      "Breakfast",
      "Lunch (Veg/Non Veg)",
      "Beers | Mineral Water",
    ],
  },
];
